### ISSUE TITLE
Publish uaa-singular to NPM

### ISSUE THREAD

**Issue by wlindner** [cloudfoundry/uaa-singular#1]
It would make it easier to integrate singular with a modern web application if it was published to [NPM](https://www.npmjs.com/).

That way it could be added to a project using the npm cli
`npm --save install uaa-singular`

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. We have published a `uaa-singular` npm package. See https://www.npmjs.com/package/uaa-singular
