### ISSUE TITLE
Display JS console error if UAA is wrong version when initializing Singular

### ISSUE THREAD

**Issue by wlindner** [cloudfoundry/uaa-singular#2]
It would be helpful if an error was displayed in the console that the UAA server Singular is connecting to is a version older than the version Singular is compatible with.

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. 

The docs currently specify the minimum version requirement of uaa server.
 
However, to assist the developer and/or help when debugging singular, `uaa-singular` could make a call to https://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#server-information and based on the `app.version` print to the browser console log if it detects that the uaa server is incompatible.

This approach would slow down the uaa-singular init time.

@sreetummidi  @jhamon  WDYT?

**Comment by DennisDenuto** [comment]
@sreetummidi Jen and I think this would be fairly simple to implement. We have a story to create a compatibility matrix in the README, but we think it would be a better user experience to also detect misconfiguration and print a helpful message for the developer. If you think that's worthwhile, please create another story for that change.
