### ISSUE TITLE
update node version 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa-singular#364]
see
https://hush-house.pivotal.io/teams/cf-uaa/pipelines/pull-requests
and failure. seems that node is < 14.x

https://stackoverflow.com/questions/70783489/fs-rmsync-throws-undefined-is-not-a-function-on-ubuntu

**Comment by peterhaochen47** [comment]
Updated and chrome driver updated, CI passes: https://hush-house.pivotal.io/teams/cf-uaa/pipelines/pull-requests/jobs/uaa-singular-tests/builds/319.1
