### ISSUE TITLE
Having issue with npm install chromedriver 2.37

### ISSUE THREAD

**Issue by shgattu** [cloudfoundry/uaa-singular#7]
Seeing below error:
 verbose stack Exit status 1
7490 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
7490 verbose stack     at emitTwo (events.js:106:13)
7490 verbose stack     at EventEmitter.emit (events.js:191:7)
7490 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
7490 verbose stack     at emitTwo (events.js:106:13)
7490 verbose stack     at ChildProcess.emit (events.js:191:7)
7490 verbose stack     at maybeClose (internal/child_process.js:886:16)
7490 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
7491 verbose pkgid chromedriver@2.37.0
7492 verbose cwd C:\Users\sgattu\Desktop\uaa-singular-master\example
7493 error Windows_NT 10.0.10586

**Comment by jhamon** [comment]
@shgattu If you checkout `45150c9b` (last commit before bumping chromedriver) are you able to successfully `npm install`? I don't have much experience troubleshooting npm issues on Windows platforms.
