### ISSUE TITLE
uaa-singular-example missing

### ISSUE THREAD

**Issue by amaline** [cloudfoundry/uaa-singular#95]
The link in the read me to uaa-singular-example is broken

**Comment by Tallicia** [comment]
This uaa-singular-example repo is no longer found in pivotal or cloudfoundry, we'll see if this can be recovered or we'll update the docs removing it. @bruce-ricard @peterhaochen47  thoughts?

**Comment by peterhaochen47** [comment]
I cannot find the original repo anymore. Let's remove the reference from the docs.

**Comment by Tallicia** [comment]
Docs Updated in https://github.com/cloudfoundry/uaa-singular/commit/bef3ba4559a7cde2d5da0f6563a50a565f4b85af
